#!/bin/bash
# With KegDemo, we want to keep some things around between CC runs (like .git).  But CC is additive,
# so we if always just run the CC on top of the repo, we could end up with files in the KegDemo repo
# that are no longer in the CC.  So this script runs before the CC in cookie-run-demo to delete
# almost everything in KegDemo ensuring a more "pristine" representation of what the CC output
# should be.

CCSRC_PATH=$(dirname $(readlink -f $0))
PROJECTS_PATH=~/projects
KEG_DEMO_SRC=$PROJECTS_PATH/keg-demo-src

find $KEG_DEMO_SRC \
    -not -path "*/.tox/*" \
    -not -path "*/.git/*" \
    -not -path "*/kegdemo-config.py" \
    -not -path "*/*.egg-info/*" \
    -delete
