#!/bin/bash -e
# Used in .circleci/config.yml to run the cookiecutter.

# Get the current directory name in a "portable" way...
CCSRC_PATH="$(dirname "$(python -c 'import os, sys; print(os.path.realpath(sys.argv[1]))' $0)")"
PROJECTS_PATH=/tmp/

cookiecutter $CCSRC_PATH --no-input --overwrite-if-exists -o $PROJECTS_PATH \
    --config-file $CCSRC_PATH/cookiecutter-ci.config

echo "keg-app-ci-src updated"
