#!/bin/bash
# Watches the CC directory and runs cookie-run-demo on any file changes.

CCSRC_PATH=$(dirname $(readlink -f $0))

export PYTHONWARNINGS=ignore::UserWarning
# watchmedo comes from https://pypi.org/project/watchdog/
watchmedo shell-command \
    --recursive \
    --command=$CCSRC_PATH/cookie-run-demo \
    $CCSRC_PATH/{{cookiecutter.project_dashed}}-src
