#!/bin/bash
CCSRC_PATH=$(dirname $(readlink -f $0))
PROJECTS_PATH=~/projects
CLEAN_SCRIPT=$CCSRC_PATH/clean-demo

$CLEAN_SCRIPT
cookiecutter $CCSRC_PATH --no-input --overwrite-if-exists -o $PROJECTS_PATH \
    --config-file $CCSRC_PATH/cookiecutter-demo.config \
&& echo "keg-demo-src updated"
