version: 2
jobs:
    build:
        docker:
            - image: level12/python-test-multi
            - image: rabbitmq:3.8
            - image: postgres:13
              environment:
                POSTGRES_USER: postgres
                # Ok for local dev, potentially UNSAFE in other applications.  Don't blindly copy
                # & paste without considering implications.
                POSTGRES_HOST_AUTH_METHOD: trust
        steps:
            - checkout
            - run: python3.9 -m pip install tox cookiecutter pip-tools
            - run:
                name: version checks
                command: |
                    pip --version
                    virtualenv --version
                    tox --version
                    cookiecutter --version
            - run:
                name: run cookiecutter
                command: ./cookie-run-ci

            - run:
                name: build requirements files
                working_directory: /tmp/keg-app-ci-src/requirements
                command: make

            - run:
                name: run the tests
                working_directory: /tmp/keg-app-ci-src
                command: tox
