version: 2
jobs:
    build:
        docker:
            - image: level12/python-test-multi
            - image: rabbitmq
            - image: postgres:9.6
              environment:
                  POSTGRES_USER: postgres
                  POSTGRES_PASSWORD: password
        steps:
            - checkout
            - run: python3.5 -m pip install tox cookiecutter pipenv==11.10.0
            - run:
                name: version checks
                command: |
                    pip --version
                    virtualenv --version
                    tox --version
                    cookiecutter --version
                    pipenv --version
            - run:
                name: run cookiecutter
                command: ./cookie-run-ci

            - run:
                name: run the tests
                working_directory: /tmp/keg-app-ci-src
                command: tox
