version: 2
jobs:
    build:
        docker:
            - image: level12/python-test-multi
            - image: postgres:9.6
              environment:
                  POSTGRES_USER: postgres
                  POSTGRES_PASSWORD: password
        steps:
            - checkout
            - run: sudo python3.5 -m pip install tox cookiecutter wheelhouse
            - run:
                name: version checks
                command: |
                    pip --version
                    virtualenv --version
                    tox --version
                    cookiecutter --version
            - run:
                name: run cookiecutter
                command: ./cookie-run-ci

            - run:
                name: build & install app requirements
                working_directory: /tmp/keg-app-ci-src
                command: |
                    wheelhouse build
                    virtualenv --python python3.5 keg-app-ci
                    . keg-app-ci/bin/activate
                    wheelhouse install -- -r requirements/dev-env.txt

            - run:
                name: run the tests
                working_directory: /tmp/keg-app-ci-src
                command: |
                    . keg-app-ci/bin/activate
                    tox
