version: 2
jobs:
    build:
        docker:
            - image: circleci/python:{{cookiecutter.python_version}}
            - image: postgres:9.6
              environment:
                  POSTGRES_USER: postgres
                  POSTGRES_PASSWORD: password
        steps:
            - checkout

            - run:
                name: folder listing for debugging
                command: ls -al

            - run:
                name: install tox from the wheelhouse
                command: >
                    sudo {{cookiecutter.python_executable}} -m pip install --upgrade --force-reinstall --quiet
                    --use-wheel --no-index --find-links=requirements/wheelhouse
                    tox

            - run:
                name: version checks
                command: |
                    {{cookiecutter.python_executable}} --version
                    {{cookiecutter.python_executable}} -m pip --version
                    {{cookiecutter.python_executable}} -m venv --version
                    tox --version

            - run:
                name: run tox
                command: tox

            - store_test_results:
                path: .ci/test-reports/

            - run:
                name: push code coverage
                command: bash <(curl -s https://codecov.io/bash) -X coveragepy -t {{cookiecutter.codecov_api_token}}
