#!/usr/bin/env python
import sys
from flake8.hooks import git_hook

if __name__ == '__main__':
    sys.exit(git_hook(
        complexity=10,
        # return non-zero depending on warnings found.  This will cause the commit to abort.
        strict=True,
        # Don't put ignore items here, put them in the flake8 config in tox.ini.
        ignore=None,
        # allows you to commit files directly (git commit -a) without going throught the index.
        lazy=True,
    ))
