# Docker Notes
# ============
# - `docker-compose up`: bring up containers
# - `docker-compose up -d`: same, but run in background/daemon mode
# - `docker-compose down`: bring down containers started with `-d`
# - `docker ps`: show running containers
# - `docker ps -a`: show all containers
# - `docker-compose exec <container name> /bin/bash`: get shell in app container
# - `docker images`
# - `docker rmi <image name>`
# - `docker stop $(docker ps -aq)`: stop all running containers
# - `docker rm $(docker ps -a -q)`: remove all stopped containers

version: '2'
services:
  {{ cookiecutter.project_dashed }}-pg:
      image: postgres:{{cookiecutter.db_postgres_version}}-alpine
      container_name: {{ cookiecutter.project_dashed }}-pg
      ports:
        - '127.0.0.1:12432:5432'
      environment:
        POSTGRES_MULTIPLE_DATABASES: {{cookiecutter.project_dashed}},{{cookiecutter.project_dashed}}-tests
        # Ok for local dev, potentially UNSAFE in other applications.  Don't blindly copy & paste
        # without considering implications.
        POSTGRES_HOST_AUTH_METHOD: trust
      volumes:
        - ./docker/pg-init-scripts:/docker-entrypoint-initdb.d
  {{ cookiecutter.project_dashed }}-rabbitmq:
      image: rabbitmq:{{cookiecutter.rabbitmq_version}}-alpine
      container_name: {{ cookiecutter.project_dashed }}-rabbitmq
      ports:
        - '127.0.0.1:12672:5672'
