#!/bin/bash

pwd
ls -la

# install tox from the wheelhouse using our target python version
{{cookiecutter.python_executable}} -m pip install --upgrade --force-reinstall \
    --quiet --use-wheel --no-index --find-links=requirements/wheelhouse tox

# run the tests using our target python version
{{cookiecutter.python_executable}} -m tox -e {{cookiecutter.python_tox}},flake8,codecov
