{% raw %}
{% set group_config -%}
    group: "{{app_cronitor_group}}"
    notify:
      - "{{app_cronitor_notification_group}}"
{%- endset %}
jobs:
  # Alive
  celery-alive-{{project_ident_env}}:
    {{group_config}}
    name: Celery Alive
    grace_seconds: 60
    realert_interval: 8 hours
    failure_tolerance: 1
    schedule_tolerance: 1
    assertions:
      - job.completes every 5 minutes
checks:
  web-{{project_ident_env}}:
    {{group_config}}
    name: Web
    schedule: every 60 seconds
    request:
      url: "https://{{nginx_vhost_server_name}}/health-check"
      timeout_seconds: 10
    assertions:
      - response.body contains vortex ok
      - "ssl_certificate.expires_in > 9"
    grace_seconds: 60
    realert_interval: 2 hours
{% endraw %}
